### ISSUE TITLE
Package extensions and meta packages

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/CounterfactualExplanations.jl#269]
Package is heavy, let's use package [extensions](https://pkgdocs.julialang.org/v1.9/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)).

Candidates are:

- [x] #301
- [ ] ~~DataFrames~~
- [x] CSV
- [x] #293
- [x] Plots (separate package) https://github.com/JuliaTrustworthyAI/.github/issues/3
- [x] Data & DataPreprocessing (separate package) https://github.com/JuliaTrustworthyAI/.github/issues/4
- [ ] ~~GenerativeModels (separate package)~~
